path: datasets
small:
  generators:
    graph500:
      scale: 4
      edge_factor: 5
  suite_sparse_matrix_list:
    - HB/ash219
    - HB/arc130
    - Averous/epb0
  suite_sparse_matrix_range:
    min_nnzs: 12
    max_nnzs: 43
    limit: 4
large:
  generators:
    graph500:
      scale: 9
      edge_factor: 10
  suite_sparse_matrix_list:
    - Simon/olafu
  suite_sparse_matrix_range:
    min_nnzs: 12
    max_nnzs: 43
    limit: 4
