path: dataset
small:
  generators:
    graph500:
      scale: 3
      edge_factor: 3
  suite_sparse_matrix_list:
    - group/mat_name
  suite_sparse_matrix_ssgetpy_util:
    min_nnzs: 12
    max_nnzs: 43
    limit: 4
large:
  generators:
    graph500:
      scale: 9
      edge_factor: 10
  suite_sparse_matrix_list:
    - group/mat_name
  suite_sparse_matrix_ssgetpy_util:
    min_nnzs: 12
    max_nnzs: 43
    limit: 4
